config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo:
      branch: master
      repo: https://gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-pumpkin-lobster.sh
        container: qc.acc_hilly-lilac-sheepdog
  QC.Doc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-mauve-bison.sh
        container: qc.doc_flabby-lilac-bison
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-magnolia-foxhound.sh
        container: qc.doc_cheeky-brown-bongo
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-harlequin-kingfisher.sh
        container: qc.doc_snippy-dandelion-quetzal
  QC.Lic:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-flax-dogfish.sh
        container: qc.lic_ready-lavender-otter
  QC.Sec:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo bandit:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-cream-zorse.sh
        container: qc.sec_chummy-cream-lion
  QC.Sty:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-sepia-chameleon.sh
        container: qc.sty_skimpy-burgundy-stingray
  QC.Uni:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo pytest:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-magnolia-wolf.sh
        container: qc.uni_lovely-seashell-mandrill
  QC.Ver:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-cerulean-wrasse.sh
        container: qc.ver_smelly-yellow-bracke
timeout: 5400
