config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo:
      branch: master
      repo: https://gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-olivine-buzzard.sh
        container: qc.acc_squeaky-seashell-cattle
  QC.Doc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-puce-toucan.sh
        container: qc.doc_shaggy-peach-ocelot
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-champagne-hummingbird.sh
        container: qc.doc_bumpy-fuchsia-avocet
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-red-russel.sh
        container: qc.doc_crappy-carmine-sponge
  QC.Lic:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-scarlet-dog.sh
        container: qc.lic_bumpy-taupe-peccary
  QC.Sec:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo bandit:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-white-flounder.sh
        container: qc.sec_lousy-cinnamon-orangutan
  QC.Sty:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-persimmon-argentino.sh
        container: qc.sty_shaky-lemon-capybara
  QC.Uni:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo pytest:
        commands:
        - /usr/bin/env sh .sqa/script.randy-auburn-duck.sh
        container: qc.uni_jumpy-buff-saola
  QC.Ver:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-gamboge-kangaroo.sh
        container: qc.ver_squeaky-ecru-gharial
timeout: 5400
