config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo:
      branch: master
      repo: https://gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-turquoise-newfoundland.sh
        container: qc.acc_grumpy-wisteria-ibis
  QC.Doc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-celadon-starfish.sh
        container: qc.doc_shaggy-thistle-insect
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-buff-hamster.sh
        container: qc.doc_grumpy-grey-jellyfish
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-chocolate-fousek.sh
        container: qc.doc_nippy-mauve-flamingo
  QC.Lic:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-apricot-sheepdog.sh
        container: qc.lic_pokey-plum-quetzal
  QC.Sec:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo bandit:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-champagne-dollar.sh
        container: qc.sec_beady-white-ant
  QC.Sty:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo flake8:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-lemon-rabbit.sh
        container: qc.sty_cloudy-tan-jellyfish
  QC.Uni:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo pytest:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-razzmatazz-albatross.sh
        container: qc.uni_woolly-dandelion-oriole
  QC.Ver:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_imo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-wisteria-angelfish.sh
        container: qc.ver_queasy-ultramarine-woodpecker
timeout: 5400
